### ISSUE TITLE
New strategy prevents locking deps with Cargo.lock

### ISSUE THREAD

**Issue by roblabla** [auxoncorp/cargo-5730#7]
To avoid having random build failures, I pin all my dependencies with Cargo.lock. In the old versions of cargo-5730 (before https://github.com/auxoncorp/cargo-5730/commit/38b0405f7bcf62b925d69bd7a411ac55900b52c5) I could simply run `cargo update` in the folder containing the build script crate, and it would generate a Cargo.lock that would get used when building/running the build script. But with the new strategy, there isn't a separate `Cargo.toml`, and so we can't have a lockfile pinning the build dependencies.

This recently bit me when a build-dependency accidentally published a breaking change, making my builds fail. IMO, cargo-5730 should have an utility to generate a `Cargo.workaround.lock` or something along those lines.

**Comment by mullr** [comment]
In the new strategy, there's a `Cargo.build.lock` file that's for this purpose exactly. Do you have that? If not, maybe there's a bug relating to that mechanism.

**Comment by roblabla** [comment]
Ah, sorry, I do have that, but it wasn't commited ^^'. This ought to be documented in the README!

**Comment by mullr** [comment]
It totally should. Update incoming.
